#!/bin/bash

# Determine the project root dynamically
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo "🔄 Syncing .env to config/config.sh..."

# Define paths
ENV_FILE="$PROJECT_ROOT/.env"
CONFIG_DIR="$PROJECT_ROOT/config"
CONFIG_FILE="$CONFIG_DIR/config.sh"
ENV_TEMPLATE="$PROJECT_ROOT/.env.template"

# Check if .env file exists
if [ ! -f "$ENV_FILE" ]; then
    echo "❌ Error: .env file not found."
    echo "Please create it from the template: cp $ENV_TEMPLATE $ENV_FILE"
    echo "Then, edit $ENV_FILE with your credentials."
    exit 1
fi

# Create config directory if it doesn't exist
if [ ! -d "$CONFIG_DIR" ]; then
    echo "Creating config directory: $CONFIG_DIR"
    mkdir -p "$CONFIG_DIR"
fi

# Copy .env content to config.sh
echo "Generating $CONFIG_FILE from $ENV_FILE..."
echo "# This file is automatically generated from .env by sync-env-to-config.sh" > "$CONFIG_FILE"
cat "$ENV_FILE" >> "$CONFIG_FILE"

# Set secure permissions for config.sh
echo "Setting secure permissions for $CONFIG_FILE..."
chmod 600 "$CONFIG_FILE"

echo "✅ Successfully synced .env to config/config.sh"
echo "Please ensure all necessary environment variables are set in $ENV_FILE."
